version: '3'
services:

  solr-database:
    image: solr:7.1.0
    ports:
      - 8983:8983
    volumes:
      - ./data:/opt/solr/server/solr/notification
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - collection1
